### ISSUE TITLE
Get Pixel Value

### ISSUE THREAD

**Issue by PatrickElsingDev** [epistemex/pngtoy#7]
This is more a question than a Issue but Documentation don´t tell me everything. ;)

How can read the color value on one Pixel with pngtoy in 16bit?

**Comment by epistemex** [comment]
Yeah, it's still in alpha so the docs aren't that complete, but I will note this one in particular. Thanks for the question :)

From the top of my head - if you're using the raw (but filtered/decoded) 16-bit bitmap the formula to get to the pixel position should be, assuming you're using the default `Uint16Array` view returned from the `decode()` method:

    var pos = width * y + x;
    var pixel = result.bitmap[pos];     // pixel value in the range [0, 65535]

**Comment by PatrickElsingDev** [comment]
Thank you @epistemex  for your fast answere.
Now I got the 16bit value.
I only have made a change for the pixelgetter.

 `
if(y <= 1){
 pixel = x-1;
                }else{
                    pixel = (width * (y-1)) + (x-1);
                }
`
