### ISSUE TITLE
Support data url?

### ISSUE THREAD

**Issue by EricBalingit** [epistemex/pngtoy#8]
`fetch()` does not work with a data url and there seems to be no other option.

**Comment by epistemex** [comment]
In what browser are you trying, and what is the error message you're getting?

Data-URIs should work as source ([test](https://jsfiddle.net/epistemex/db09axcy/))

**Comment by EricBalingit** [comment]
Ah, pardon my ignorance.  I was testing on Khan Academy and it is a CORS issue, but I cannot resolve it from within the sandbox.  Would be nice though to have a blocking alternative in case the need ever arises. ;P

Also, the documentation is not very clear for anyone unfamiliar with promises.  I had to look at the source code to figure out how to get this far.

**Comment by EricBalingit** [comment]
Closing this issue.

**Comment by epistemex** [comment]
Yeah, it's still in alpha so not everything is in place. CORS and promises are initially out of scope for the documentation, but we'll consider including a section/example for it. In any case, thanks for the feedback as well as interest in the project.
